"""create vehicles table

Revision ID: 8ed136ce69e6
Revises: 551ff659db3e
Create Date: 2026-10-11 06:12:58.004923
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '8ed136ce69e6'
down_revision: str | Sequence[str] | None = '551ff659db3e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=True),
    sa.Column('registration_number', sa.String(length=10), nullable=False),
    sa.Column('make', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=30), nullable=False),
    sa.Column('variant', sa.String(length=45), nullable=False),
    sa.Column('vehicle_type', sa.String(length=25), nullable=False),
    sa.Column('fuel_type', sa.String(length=10), nullable=False),
    sa.Column('transmission', sa.String(length=15), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('vin', sa.String(length=20), nullable=False),
    sa.Column('odometer', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('chassis_number', sa.String(length=20), nullable=True),
    sa.Column('manufacture_year', sa.Integer(), nullable=True),
    sa.Column('engine_capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fuel_type IN ('petrol', 'diesel', 'ev', 'cng', 'hybrid')", name='fuel_type_check'),
    sa.CheckConstraint("transmission IN ('manual', 'semi_automatic', 'automatic')", name='transmission_check'),
    sa.CheckConstraint("vehicle_type IN ('private', 'commercial')", name='vehicle_type_check'),
    sa.CheckConstraint('engine_capacity >= 998', name='engine_cc_check'),
    sa.CheckConstraint('manufacture_year >= 1970', name='vehicle_manufacture_year_check'),
    sa.CheckConstraint('odometer > 0', name='odometer_reading_check'),
    sa.ForeignKeyConstraint(['cust_id'], ['customers.id'], name='cust_vehicles_key', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    # ### end Alembic commands ###
